### ISSUE TITLE
缺少远程异常提示

### ISSUE THREAD

**Issue by xljiulang** [ihaoqihao/FastSocket.Net#3]
服务端在运行时，难免会出现一些不可觉察的且未做过处理的异常，造成客户端无法获知这些异常而一直等待到超时抛出超时异常，这两个异常不是同一种异常。

可以参考
https://github.com/xljiulang/NetworkSocket/tree/master/Net40/NetworkSocket/Fast

实现远程端异常后，客户端可以如此编码：
private async void btn_Login_Click(object sender, EventArgs e)
        {
            var user = new User
            {
                Account = this.textBox_Account.Text,
                Password = this.textBox_Password.Text
            };

```
        try
        {
            var state = await RemoteServer.Instance.Login(user, false);
            MessageBox.Show("登录" + (state ? "成功" : "失败"));
        }
        catch (TimeoutException ex)
        {
            this.Text = ex.Message;
        }
        catch (RemoteException ex)
        {
            MessageBox.Show(ex.Message, "远程服务器异常");
        }
    }
```

**Comment by ihaoqihao** [comment]
这属于自定义协议里做的事情，比如redis协议http://www.cnblogs.com/me-sa/archive/2011/12/06/erlang0019.html

其中响应消息的第一个字节表示了消息的类型:
单行消息 "+"
错误消息 "-"
返回一个整型值 ":"
返回bulk reply "$"
返回multi-bulk reply "*"

服务端将异常序列化后响应给客户端请求，客户端进行要应解析并throw异常(比如redis协议，当消息类型为"-"时，则读取redis返回的exception message，然后包装成一个Exception并throw)
